<ul>	</ul>
<center><li> 	Dernière pluie (>1 mm) le $last_rain ( il y a $time_since_last_rain.long_form ) </li></center>
<ul>	</ul>
<div class="snapshot-records-text">
<iframe seamless width="888" height="336" frameborder="0" src="https://www.infoclimat.fr/public-api/mixed/iframeSLIDE?_ll=48.70049,1.88696&_inc=WyJBdWZmYXJnaXMiLCIxNTciLCIzMDM2MjIzIiwiRlIiXQ==&_auth=BR9UQwN9BCZTflJlBHJQeQNrBzIJfwAnUS0HZAlsBHkFYVA0AmFXMV85AXxQfwA1VXgEbFtsBTsHbVIzDnxUKAVlVDADYwRgUz5SMgQ3UHsDLwdiCTAAP1E0B2MJewR4BW5QPQJ%2FVz1fMwF9UGEAM1VgBHpbbAU6B3tSKg5iVDIFb1QyA2QEZVM8UjAEMlBkAy8HeAkzAG1RZwcxCWwEMwUzUGcCaVc1X2IBYFBjADZVeARhW2MFPwdhUjAOZVQzBWFULwN%2FBB9TT1ItBHRQJgNlByEJKwBtUWwHNA%3D%3D&_c=4a1adc3ac5610103c8d65d8338e051a5"></iframe>
</div>
<div class="snapshot-records-text">
<iframe seamless width="888" height="666" frameborder="0" src="https://earth.nullschool.net/fr/#current/wind/surface/level/overlay=temp/orthographic=-4.36,49.07,1022/loc=1.882,48.701"></iframe>
</div>
